namespace DigitalLearningSolutions.Data.Migrations
{
    using FluentMigrator;
    [Migration(202312151357)]
    public class DeprecateUnusedTables : Migration
    {
        public override void Up()
        {
            Rename.Table("ApplicationGroups").To("deprecated_ApplicationGroups");
            Rename.Table("aspProgressLearningLogItems").To("deprecated_aspProgressLearningLogItems");
            Rename.Table("aspSelfAssessLog").To("deprecated_aspSelfAssessLog");
            Rename.Table("AssessmentTypeDescriptors").To("deprecated_AssessmentTypeDescriptors");
            Rename.Table("AssessmentTypes").To("deprecated_AssessmentTypes");
            Rename.Table("Browsers").To("deprecated_Browsers");
            Rename.Table("ConsolidationRatings").To("deprecated_ConsolidationRatings");
            Rename.Table("ContributorRoles").To("deprecated_ContributorRoles");
            Rename.Table("EmailDupExclude").To("deprecated_EmailDupExclude");
            Rename.Table("FilteredComptenencyMapping").To("deprecated_FilteredComptenencyMapping");
            Rename.Table("FilteredSeniorityMapping").To("deprecated_FilteredSeniorityMapping");
            Rename.Table("FollowUpFeedback").To("deprecated_FollowUpFeedback");
            Rename.Table("KBCentreBrandsExcludes").To("deprecated_KBCentreBrandsExcludes");
            Rename.Table("KBCentreCategoryExcludes").To("deprecated_KBCentreCategoryExcludes");
            Rename.Table("kbLearnTrack").To("deprecated_kbLearnTrack");
            Rename.Table("kbSearches").To("deprecated_kbSearches");
            Rename.Table("kbVideoTrack").To("deprecated_kbVideoTrack");
            Rename.Table("kbYouTubeTrack").To("deprecated_kbYouTubeTrack");
            Rename.Table("LearnerPortalProgressKeys").To("deprecated_LearnerPortalProgressKeys");
            Rename.Table("NonCompletedFeedback").To("deprecated_NonCompletedFeedback");
            Rename.Table("OfficeApplications").To("deprecated_OfficeApplications");
            Rename.Table("OfficeVersions").To("deprecated_OfficeVersions");
            Rename.Table("OrderLines").To("deprecated_OrderLines");
            Rename.Table("Orders").To("deprecated_Orders");
            Rename.Table("pl_CaseContent").To("deprecated_pl_CaseContent");
            Rename.Table("pl_CaseStudies").To("deprecated_pl_CaseStudies");
            Rename.Table("pl_Features").To("deprecated_pl_Features");
            Rename.Table("pl_Products").To("deprecated_pl_Products");
            Rename.Table("pl_Quotes").To("deprecated_pl_Quotes");
            Rename.Table("Products").To("deprecated_Products");
            Rename.Table("ProgressContributors").To("deprecated_ProgressContributors");
            Rename.Table("ProgressKeyCheckLog").To("deprecated_ProgressKeyCheckLog");
            Rename.Table("pwBulletins").To("deprecated_pwBulletins");
            Rename.Table("pwCaseStudies").To("deprecated_pwCaseStudies");
            Rename.Table("pwNews").To("deprecated_pwNews");
            Rename.Table("pwVisits").To("deprecated_pwVisits");
            Rename.Table("VideoRatings").To("deprecated_VideoRatings");
        }
        public override void Down()
        {
            Rename.Table("deprecated_ApplicationGroups").To("ApplicationGroups");
            Rename.Table("deprecated_aspProgressLearningLogItems").To("aspProgressLearningLogItems");
            Rename.Table("deprecated_aspSelfAssessLog").To("aspSelfAssessLog");
            Rename.Table("deprecated_AssessmentTypeDescriptors").To("AssessmentTypeDescriptors");
            Rename.Table("deprecated_AssessmentTypes").To("AssessmentTypes");
            Rename.Table("deprecated_Browsers").To("Browsers");
            Rename.Table("deprecated_ConsolidationRatings").To("ConsolidationRatings");
            Rename.Table("deprecated_ContributorRoles").To("ContributorRoles");
            Rename.Table("deprecated_EmailDupExclude").To("EmailDupExclude");
            Rename.Table("deprecated_FilteredComptenencyMapping").To("FilteredComptenencyMapping");
            Rename.Table("deprecated_FilteredSeniorityMapping").To("FilteredSeniorityMapping");
            Rename.Table("deprecated_FollowUpFeedback").To("FollowUpFeedback");
            Rename.Table("deprecated_KBCentreBrandsExcludes").To("KBCentreBrandsExcludes");
            Rename.Table("deprecated_KBCentreCategoryExcludes").To("KBCentreCategoryExcludes");
            Rename.Table("deprecated_kbLearnTrack").To("kbLearnTrack");
            Rename.Table("deprecated_kbSearches").To("kbSearches");
            Rename.Table("deprecated_kbVideoTrack").To("kbVideoTrack");
            Rename.Table("deprecated_kbYouTubeTrack").To("kbYouTubeTrack");
            Rename.Table("deprecated_LearnerPortalProgressKeys").To("LearnerPortalProgressKeys");
            Rename.Table("deprecated_NonCompletedFeedback").To("NonCompletedFeedback");
            Rename.Table("deprecated_OfficeApplications").To("OfficeApplications");
            Rename.Table("deprecated_OfficeVersions").To("OfficeVersions");
            Rename.Table("deprecated_OrderLines").To("OrderLines");
            Rename.Table("deprecated_Orders").To("Orders");
            Rename.Table("deprecated_pl_CaseContent").To("pl_CaseContent");
            Rename.Table("deprecated_pl_CaseStudies").To("pl_CaseStudies");
            Rename.Table("deprecated_pl_Features").To("pl_Features");
            Rename.Table("deprecated_pl_Products").To("pl_Products");
            Rename.Table("deprecated_pl_Quotes").To("pl_Quotes");
            Rename.Table("deprecated_Products").To("Products");
            Rename.Table("deprecated_ProgressContributors").To("ProgressContributors");
            Rename.Table("deprecated_ProgressKeyCheckLog").To("ProgressKeyCheckLog");
            Rename.Table("deprecated_pwBulletins").To("pwBulletins");
            Rename.Table("deprecated_pwCaseStudies").To("pwCaseStudies");
            Rename.Table("deprecated_pwNews").To("pwNews");
            Rename.Table("deprecated_pwVisits").To("pwVisits");
            Rename.Table("deprecated_VideoRatings").To("VideoRatings");
        }
    }
}

