namespace DigitalLearningSolutions.Data.Migrations
{
    using FluentMigrator;
    [Migration(202401231524)]
    public class DropUnusedTables : Migration
    {
        public override void Up()
        {
            Delete.ForeignKey("FK_ApplicationGroups_ApplicationGroups").OnTable("deprecated_ApplicationGroups");
            Delete.ForeignKey("FK_Applications_ApplicationGroups").OnTable("Applications");
            Delete.ForeignKey("FK_aspProgressLearningLogItems_aspProgress").OnTable("deprecated_aspProgressLearningLogItems");
            Delete.ForeignKey("FK_ConsolidationRatings_Sections").OnTable("deprecated_ConsolidationRatings");
            Delete.ForeignKey("FK_FilteredComptenencyMapping_CompetencyID_Competencies_ID").OnTable("deprecated_FilteredComptenencyMapping");
            Delete.ForeignKey("FK_FilteredSeniorityMapping_CompetencyGroupID_CompetencyGroups_ID").OnTable("deprecated_FilteredSeniorityMapping");
            Delete.ForeignKey("FK_KBCentreBrandsExcludes_Brands").OnTable("deprecated_KBCentreBrandsExcludes");
            Delete.ForeignKey("FK_KBCentreBrandsExcludes_Centres").OnTable("deprecated_KBCentreBrandsExcludes");
            Delete.ForeignKey("FK_KBCentreCategoryExcludes_Centres").OnTable("deprecated_KBCentreCategoryExcludes");
            Delete.ForeignKey("FK_KBCentreCategoryExcludes_CourseCategories").OnTable("deprecated_KBCentreCategoryExcludes");
            Delete.ForeignKey("FK_tKBVideoTrack_Candidates").OnTable("deprecated_kbVideoTrack");
            Delete.ForeignKey("FK_tKBVideoTrack_Tutorials").OnTable("deprecated_kbVideoTrack");
            Delete.ForeignKey("FK_OrderLines_Orders").OnTable("deprecated_OrderLines");
            Delete.ForeignKey("FK_OrderLines_Products").OnTable("deprecated_OrderLines");
            Delete.ForeignKey("FK_Orders_Centres").OnTable("deprecated_Orders");
            Delete.ForeignKey("FK_pl_CaseContent_pl_CaseStudies").OnTable("deprecated_pl_CaseContent");
            Delete.ForeignKey("FK_pl_CaseStudies_Brands").OnTable("deprecated_pl_CaseStudies");
            Delete.ForeignKey("FK_pl_CaseStudies_pl_Products").OnTable("deprecated_pl_CaseStudies");
            Delete.ForeignKey("FK_pl_Features_pl_Products").OnTable("deprecated_pl_Features");
            Delete.ForeignKey("FK_pl_Quotes_Brands").OnTable("deprecated_pl_Quotes");
            Delete.ForeignKey("FK_pl_Quotes_Products").OnTable("deprecated_pl_Quotes");
            Delete.ForeignKey("FK_ProgressContributors_Progress").OnTable("deprecated_ProgressContributors");
            Delete.ForeignKey("FK_pwNews_Brands").OnTable("deprecated_pwNews");
            Delete.ForeignKey("FK_pwNews_pl_Products").OnTable("deprecated_pwNews");
            Delete.ForeignKey("FK_VideoRatings_Tutorials").OnTable("deprecated_VideoRatings");
            Delete.Table("deprecated_ApplicationGroups");
            Delete.Table("deprecated_aspProgressLearningLogItems");
            Delete.Table("deprecated_aspSelfAssessLog");
            Delete.Table("deprecated_AssessmentTypeDescriptors");
            Delete.Table("deprecated_AssessmentTypes");
            Delete.Table("deprecated_Browsers");
            Delete.Table("deprecated_ConsolidationRatings");
            Delete.Table("deprecated_ContributorRoles");
            Delete.Table("deprecated_EmailDupExclude");
            Delete.Table("deprecated_FilteredComptenencyMapping");
            Delete.Table("deprecated_FilteredSeniorityMapping");
            Delete.Table("deprecated_FollowUpFeedback");
            Delete.Table("deprecated_KBCentreBrandsExcludes");
            Delete.Table("deprecated_KBCentreCategoryExcludes");
            Delete.Table("deprecated_kbLearnTrack");
            Delete.Table("deprecated_kbSearches");
            Delete.Table("deprecated_kbVideoTrack");
            Delete.Table("deprecated_kbYouTubeTrack");
            Delete.Table("deprecated_LearnerPortalProgressKeys");
            Delete.Table("deprecated_NonCompletedFeedback");
            Delete.Table("deprecated_OfficeApplications");
            Delete.Table("deprecated_OfficeVersions");
            Delete.Table("deprecated_OrderLines");
            Delete.Table("deprecated_Orders");
            Delete.Table("deprecated_pl_CaseContent");
            Delete.Table("deprecated_pl_CaseStudies");
            Delete.Table("deprecated_pl_Features");
            Delete.Table("deprecated_pl_Products");
            Delete.Table("deprecated_pl_Quotes");
            Delete.Table("deprecated_Products");
            Delete.Table("deprecated_ProgressContributors");
            Delete.Table("deprecated_ProgressKeyCheckLog");
            Delete.Table("deprecated_pwBulletins");
            Delete.Table("deprecated_pwCaseStudies");
            Delete.Table("deprecated_pwNews");
            Delete.Table("deprecated_pwVisits");
            Delete.Table("deprecated_VideoRatings");
        }
        public override void Down()
        {
            Execute.Sql(Properties.Resources.TD_3629_DeleteDeprecatedTables_DOWN);
        }
    }
}

