//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLearningSolutions.Data.Migrations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalLearningSolutions.Data.Migrations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 16/10/2020
        ///-- Description:	Updates a customisation based on form values
        ///-- V2 Adds @CCEmail
        ///-- V3 Adds ApplyLPDefaultsToSelfEnrol
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[UpdateCustomisation_V3]
        ///	-- Add the parameters for the stored procedure here
        ///	@CustomisationID As Int,
        ///	@Active as bit,
        ///	@CustomisationName as nvarcha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplyLPDefaultsSPChanges {
            get {
                return ResourceManager.GetString("ApplyLPDefaultsSPChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 15 February 2012
        ///-- Description:	Creates the Progress and aspProgress record for a new user
        ///-- Returns:		0 : success, progress created
        ///--       		1 : Failed - progress already exists
        ///--       		100 : Failed - CentreID and CustomisationID don&apos;t match
        ///--       		101 : Failed - CentreID and CandidateID don&apos;t match
        ///
        ///-- V3 changes include:
        ///
        ///-- Checks that  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DropApplyLPDefaultsSPChanges {
            get {
                return ResourceManager.GetString("DropApplyLPDefaultsSPChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DROP PROCEDURE [dbo].[GetFilteredCompetencyResponsesForCandidate]
        ///GO
        ///DROP PROCEDURE [dbo].[GetFilteredProfileForCandidate]
        ///GO
        ///DROP FUNCTION [dbo].[GetSelfAssessmentSummaryForCandidate]
        ///GO
        ///DROP FUNCTION [dbo].[GetFilteredAPISeniorityID]
        ///GO
        ///
        ///
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string DropFilteredSPs {
            get {
                return ResourceManager.GetString("DropFilteredSPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]
        ///GO.
        /// </summary>
        internal static string DropGetActiveAvailableV5 {
            get {
                return ResourceManager.GetString("DropGetActiveAvailableV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE FUNCTION [dbo].[GetSelfAssessmentSummaryForCandidate]
        ///(
        ///	@CandidateID int,
        ///	@SelfAssessmentID int
        ///)
        ///RETURNS @ResTable TABLE 
        ///(
        ///	CompetencyGroupID int,
        ///	Confidence float,
        ///	Relevance float
        ///)
        ///
        ///AS	  
        ///BEGIN
        ///INSERT INTO @ResTable
        ///	SELECT CompetencyGroupID, [1] AS Confidence, [2] AS Relevance
        ///FROM   (SELECT comp.CompetencyGroupID, sar.AssessmentQuestionID, sar.Result*1.0 AS Result
        ///             FROM    Competencies AS comp INNER JOIN
        ///                           SelfAssessmentResults AS sar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilteredSPs {
            get {
                return ResourceManager.GetString("FilteredSPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]    Script Date: 14/10/2020 10:02:34 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 05/10/2020
        ///-- Description:	Returns active available customisations for centre v5 adds SelfAssessments.
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetActiveAvailableV5 {
            get {
                return ResourceManager.GetString("GetActiveAvailableV5", resourceCulture);
            }
        }
    }
}
