//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLearningSolutions.Data.Migrations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalLearningSolutions.Data.Migrations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 16/10/2020
        ///-- Description:	Updates a customisation based on form values
        ///-- V2 Adds @CCEmail
        ///-- V3 Adds ApplyLPDefaultsToSelfEnrol
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[UpdateCustomisation_V3]
        ///	-- Add the parameters for the stored procedure here
        ///	@CustomisationID As Int,
        ///	@Active as bit,
        ///	@CustomisationName as nvarcha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplyLPDefaultsSPChanges {
            get {
                return ResourceManager.GetString("ApplyLPDefaultsSPChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=nhsuk-u-reading-width&gt;&lt;h2&gt;What are cookies?&lt;/h2&gt;&lt;p&gt;Cookies are files saved on your phone, tablet or computer when you visit a website.&lt;p&gt;They store information about how you use the website, such as the pages you visit.&lt;p&gt;Cookies are not viruses or computer programs. They are very small so do not take up much space.&lt;h2&gt;How we use cookies&lt;/h2&gt;&lt;p&gt;We only use cookies to:&lt;ul&gt;&lt;li&gt;make our website work&lt;li&gt;measure how you use our website, such as which links you click on (analytics cookies), if you give [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CookiePolicy {
            get {
                return ResourceManager.GetString("CookiePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 04/01/2021
        ///-- Description:	Reorders the FrameworkCompetencyGroups in a given Framework - moving the given group up or down.
        ///-- =============================================
        ///CREATE OR ALTER PROCEDURE [dbo].[ReorderFrameworkCompetencyGroup]
        ///	-- Add the parameters for the stored procedure here
        ///	@FrameworkCompetencyGroupID int,
        ///	@Direction nvarchar(4) = &apos;&apos;,
        ///	@SingleStep bit
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateOrAlterReorderFrameworkCompetenciesAndGroupsSPs {
            get {
                return ResourceManager.GetString("CreateOrAlterReorderFrameworkCompetenciesAndGroupsSPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[InsertCustomisation_V3]    Script Date: 20/11/2020 14:12:52 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 28 February 2020
        ///-- V2 Adds @CCCompletion field
        ///-- =============================================
        ///CREATE OR ALTER PROCEDURE [dbo].[InsertCustomisation_V3] 
        ///	@Active as bit,
        ///	@ApplicationID as int,
        ///	@CentreID as int,
        ///	@CustomisationName as nvarch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_106_CreateOrAlterInsertCustomisation_V3 {
            get {
                return ResourceManager.GetString("DLSV2_106_CreateOrAlterInsertCustomisation_V3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[InsertCustomisation_V3]    Script Date: 20/11/2020 14:12:52 ******/
        ///DROP PROCEDURE [dbo].[InsertCustomisation_V3]
        ///GO
        ///
        ///
        ///.
        /// </summary>
        internal static string DLSV2_106_DropInsertCustomisation_V3 {
            get {
                return ResourceManager.GetString("DLSV2_106_DropInsertCustomisation_V3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetFilteredCompetencyResponsesForCandidate]    Script Date: 22/09/2020 09:22:43 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 22/09/2020
        ///-- Description:	Returns user self assessment responses (AVG) for Filtered competency
        ///-- =============================================
        ///CREATE OR ALTER PROCEDURE [dbo].[GetFilteredCompetencyResponsesForCandidate]
        ///	-- Add t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_133_AdjustScoresForFilteredSP {
            get {
                return ResourceManager.GetString("DLSV2_133_AdjustScoresForFilteredSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetFilteredCompetencyResponsesForCandidate]    Script Date: 22/09/2020 09:22:43 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 22/09/2020
        ///-- Description:	Returns user self assessment responses (AVG) for Filtered competency
        ///-- =============================================
        ///CREATE OR ALTER PROCEDURE [dbo].[GetFilteredCompetencyResponsesForCandidate]
        ///	-- Add t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_133_UnAdjustScoresForFilteredSP {
            get {
                return ResourceManager.GetString("DLSV2_133_UnAdjustScoresForFilteredSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////****** Object:  UserDefinedFunction [dbo].[GetSelfAssessmentSummaryForCandidate]    Script Date: 28/01/2021 07:45:22 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE OR ALTER FUNCTION [dbo].[GetSelfAssessmentSummaryForCandidate]
        ///(
        ///	@CandidateID int,
        ///	@SelfAssessmentID int
        ///)
        ///RETURNS @ResTable TABLE 
        ///(
        ///	CompetencyGroupID int,
        ///	Confidence float,
        ///	Relevance float
        ///)
        ///
        ///AS	  
        ///BEGIN
        ///INSERT INTO @ResTable
        ///	SELECT CompetencyGroupID, [1] AS Confidence, [2] AS Relevance
        ///FROM    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_153_DropFilteredFunctionTweak {
            get {
                return ResourceManager.GetString("DLSV2_153_DropFilteredFunctionTweak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////****** Object:  StoredProcedure [dbo].[GetFilteredCompetencyResponsesForCandidate]    Script Date: 27/01/2021 16:01:15 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 22/09/2020
        ///-- Description:	Returns user self assessment responses (AVG) for Filtered competency
        ///-- =============================================
        ///CREATE OR ALTER PROCEDURE [dbo].[GetFilteredCompetencyResponsesForCandidate]
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_153_DropFilteredSPFixes {
            get {
                return ResourceManager.GetString("DLSV2_153_DropFilteredSPFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  UserDefinedFunction [dbo].[GetSelfAssessmentSummaryForCandidate]    Script Date: 28/01/2021 07:43:39 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE OR ALTER FUNCTION [dbo].[GetSelfAssessmentSummaryForCandidate]
        ///(
        ///	@CandidateID int,
        ///	@SelfAssessmentID int
        ///)
        ///RETURNS @ResTable TABLE 
        ///(
        ///	CompetencyGroupID int,
        ///	Confidence float,
        ///	Relevance float
        ///)
        ///
        ///AS	  
        ///BEGIN
        ///INSERT INTO @ResTable
        ///	SELECT CompetencyGroupID, [1] AS Confidence, [2] AS Relevance
        ///FROM   (SELEC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_153_FilteredFunctionTweak {
            get {
                return ResourceManager.GetString("DLSV2_153_FilteredFunctionTweak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetFilteredCompetencyResponsesForCandidate]    Script Date: 27/01/2021 15:29:35 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 22/09/2020
        ///-- Description:	Returns user self assessment responses (AVG) for Filtered competency
        ///-- =============================================
        ///CREATE OR ALTER   PROCEDURE [dbo].[GetFilteredCompetencyResponsesForCandidate]
        ///	-- Add [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_153_FilteredSPFixes {
            get {
                return ResourceManager.GetString("DLSV2_153_FilteredSPFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[InsertUpdateCustomisationTutorials]    Script Date: 21/04/2021 16:16:32 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 02/03/2020
        ///-- Description:	Updates or inserts a CustomisationTutorials record  with new values
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[InsertUpdateCustomisationTutorials]
        ///	-- Add the parameters for the store [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dlsv2_172_fixcustomisationtutorialprogressissue_down {
            get {
                return ResourceManager.GetString("dlsv2_172_fixcustomisationtutorialprogressissue_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[InsertUpdateCustomisationTutorials]    Script Date: 21/04/2021 16:16:32 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 02/03/2020
        ///-- Description:	Updates or inserts a CustomisationTutorials record  with new values
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[InsertUpdateCustomisationTutorials]
        ///	-- Add the parameters for the store [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dlsv2_172_fixcustomisationtutorialprogressissue_up {
            get {
                return ResourceManager.GetString("dlsv2_172_fixcustomisationtutorialprogressissue_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetCompletedCoursesForCandidate]    Script Date: 21/06/2021 08:36:32 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 16/12/2016
        ///-- Description:	Returns a list of completed courses for the candidate.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GetCompletedCoursesForCandidate]
        ///	-- Add the parameters for the stored procedure here
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_236_GetCompletedCoursesTweak_DOWN {
            get {
                return ResourceManager.GetString("DLSV2_236_GetCompletedCoursesTweak_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetCompletedCoursesForCandidate]    Script Date: 21/06/2021 08:36:32 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 16/12/2016
        ///-- Description:	Returns a list of completed courses for the candidate.
        ///-- 21/06/2021: Adds Applications.ArchivedDate field to output.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GetCompletedCoursesForCan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_236_GetCompletedCoursesTweak_UP {
            get {
                return ResourceManager.GetString("DLSV2_236_GetCompletedCoursesTweak_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]    Script Date: 22/06/2021 09:46:28 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 05/10/2020
        ///-- Description:	Returns active available customisations for centre v5 adds SelfAssessments.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFilter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_237_GetActiveAvailableTweak_DOWN {
            get {
                return ResourceManager.GetString("DLSV2_237_GetActiveAvailableTweak_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]    Script Date: 22/06/2021 09:46:28 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 05/10/2020
        ///-- Description:	Returns active available customisations for centre v5 adds SelfAssessments.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFilter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_237_GetActiveAvailableTweak_UP {
            get {
                return ResourceManager.GetString("DLSV2_237_GetActiveAvailableTweak_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  UserDefinedFunction [dbo].[GetLinkedFieldNameForCentreByID]    Script Date: 16/07/2021 09:23:22 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 12/10/2018
        ///-- Description:	Return the field name for centre group linked field ID
        ///-- =============================================
        ///ALTER FUNCTION [dbo].[GetLinkedFieldNameForCentreByID] 
        ///(
        ///	-- Add the parameters for the function here
        ///	@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_272_AlterGetLinkedFieldNameFunction_DOWN {
            get {
                return ResourceManager.GetString("DLSV2_272_AlterGetLinkedFieldNameFunction_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  UserDefinedFunction [dbo].[GetLinkedFieldNameForCentreByID]    Script Date: 16/07/2021 09:23:22 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 12/10/2018
        ///-- Description:	Return the field name for centre group linked field ID
        ///-- =============================================
        ///ALTER FUNCTION [dbo].[GetLinkedFieldNameForCentreByID] 
        ///(
        ///	-- Add the parameters for the function here
        ///	@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_272_AlterGetLinkedFieldNameFunction_UP {
            get {
                return ResourceManager.GetString("DLSV2_272_AlterGetLinkedFieldNameFunction_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[ReorderFrameworkCompetency]    Script Date: 15/10/2021 08:31:18 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 15/10/2021
        ///-- Description:	Reorders the CompetencyAssessmentQuestions - moving the given competency question up or down.
        ///-- =============================================
        ///CREATE OR ALTER   PROCEDURE [dbo].[ReorderCompetencyAssessmentQuestion]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_379_ReorderCompetencyAssessmentQuestionsSP {
            get {
                return ResourceManager.GetString("DLSV2_379_ReorderCompetencyAssessmentQuestionsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V6]    Script Date: 29/09/2022 19:11:04 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Manish Agarwal
        ///-- Create date: 26/09/2022
        ///-- Description:	Returns active available customisations for centre v6 adds SelfAssessments.
        ///-- =============================================
        ///CREATE OR ALTER PROCEDURE [dbo].[GetActiveAvailableCustomisationsFo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_581_GetActiveAvailableCustomisationsForCentreFiltered_V6 {
            get {
                return ResourceManager.GetString("DLSV2_581_GetActiveAvailableCustomisationsForCentreFiltered_V6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DLSV2-95 Adds System Versioning to auditable tables (UP)
        ///
        ///--Frameworks table
        ///ALTER TABLE Frameworks
        ///    ADD
        ///        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
        ///            CONSTRAINT DF_Frameworks_SysStart DEFAULT SYSUTCDATETIME()
        ///      , SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
        ///            CONSTRAINT DF_Frameworks_SysEnd DEFAULT CONVERT(DATETIME2, &apos;9999-12-31 23:59:59.9999999&apos;),
        ///        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);
        ///GO
        ///
        ///ALTER TABLE Framework [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_95_AddSystemVersioning {
            get {
                return ResourceManager.GetString("DLSV2_95_AddSystemVersioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DLSV2-95 Removes System Versioning to auditable tables (DOWN)
        ///
        ///
        ///-- Remove versioning from FrameworkCompetencies table
        ///ALTER TABLE FrameworkCompetencies SET (SYSTEM_VERSIONING = OFF);
        ///DROP TABLE dbo.FrameworkCompetencies;
        ///DROP TABLE dbo.FrameworkCompetenciesHistory;
        ///GO
        ///
        ///-- Remove versioning from FrameworkCompetencyGroups table
        ///ALTER TABLE FrameworkCompetencyGroups SET (SYSTEM_VERSIONING = OFF);
        ///DROP TABLE dbo.FrameworkCompetencyGroups;
        ///DROP TABLE dbo.FrameworkCompetencyGroupsHistory;
        ///GO
        ///
        ///--  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLSV2_95_RemoveSystemVersioning {
            get {
                return ResourceManager.GetString("DLSV2_95_RemoveSystemVersioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V6]    Script Date: 03/10/2022 06:00:00 ******/
        ///DROP PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V6]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string DropActiveAvailableV6 {
            get {
                return ResourceManager.GetString("DropActiveAvailableV6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 䕓⁔乁䥓也䱕卌传ൎ䜊൏匊呅儠何䕔彄䑉久䥔䥆剅传ൎ䜊൏ഊⴊ‭㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽ഽⴊ‭畁桴牯ऺ䬉癥湩圠楨瑴歡牥਍ⴭ䌠敲瑡⁥慤整›㔱䘠扥畲牡⁹〲㈱਍ⴭ䐠獥牣灩楴湯ऺ牃慥整⁳桴⁥牐杯敲獳愠摮愠灳牐杯敲獳爠捥牯⁤潦⁲⁡敮⁷獵牥਍ⴭ删瑥牵獮ऺ〉㨠猠捵散獳‬牰杯敲獳挠敲瑡摥਍ⴭ†††ठㄉ㨠䘠楡敬⁤‭牰杯敲獳愠牬慥祤攠楸瑳൳ⴊ‭†††उ〱‰›慆汩摥ⴠ䌠湥牴䥥⁄湡⁤畃瑳浯獩瑡潩䥮⁄潤❮⁴慭捴൨ⴊ‭†††उ〱‱›慆汩摥ⴠ䌠湥牴䥥⁄湡⁤慃摮摩瑡䥥⁄潤❮⁴慭捴൨ഊⴊ‭㍖挠慨杮獥椠据畬敤ഺഊⴊ‭桃捥獫琠慨⁴硥獩楴杮瀠潲牧獥⁳慨湳琧戠敥⁮敒潭敶⁤牯删晥敲桳摥戠晥牯⁥敲畴楲楮杮攠牲牯മⴊ‭摁獤瀠牡浡瑥牥⁳潦⁲湅潲汬敭瑮洠瑥潨⁤湡⁤摡業⁮䑉਍ⴭ㴠㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽਍䱁䕔⁒剐䍏䑅剕⁅摛潢⹝畛灳牃慥整牐杯敲獳敒潣摲噟崳਍䀉慃摮摩瑡䥥⁄湩ⱴ਍䀉畃瑳浯獩瑡潩䥮⁄湩ⱴ਍䀉敃瑮敲䑉椠瑮ബऊ䕀牮汯浬湥䵴瑥潨䥤⁄湩ⱴ਍䀉湅潲汬摥祂摁業䥮⁄湩൴䄊൓䈊䝅义਍ⴉ‭䕓⁔低佃乕⁔乏愠摤摥琠⁯牰癥湥⁴硥牴⁡敲畳瑬猠瑥⁳牦浯਍ⴉ‭湩整晲牥湩⁧楷桴匠䱅䍅⁔瑳瑡浥湥獴മऊ䕓⁔低佃乕⁔乏഻ऊⴭ਍ⴉ‭桔牥⁥牡⁥慶楲畯⁳桴湩獧琠 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DropApplyLPDefaultsSPChanges {
            get {
                return ResourceManager.GetString("DropApplyLPDefaultsSPChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DROP PROCEDURE [dbo].[GetFilteredCompetencyResponsesForCandidate]
        ///GO
        ///DROP PROCEDURE [dbo].[GetFilteredProfileForCandidate]
        ///GO
        ///DROP FUNCTION [dbo].[GetSelfAssessmentSummaryForCandidate]
        ///GO
        ///DROP FUNCTION [dbo].[GetFilteredAPISeniorityID]
        ///GO
        ///
        ///
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string DropFilteredSPs {
            get {
                return ResourceManager.GetString("DropFilteredSPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]
        ///GO.
        /// </summary>
        internal static string DropGetActiveAvailableV5 {
            get {
                return ResourceManager.GetString("DropGetActiveAvailableV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[ReorderTutorial]    Script Date: 04/01/2021 16:17:57 ******/
        ///DROP PROCEDURE [dbo].[ReorderFrameworkCompetency]
        ///GO
        ///DROP PROCEDURE [dbo].[ReorderFrameworkCompetencyGroup]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string DropReorderFrameworkCompetenciesAndGroupsSPs {
            get {
                return ResourceManager.GetString("DropReorderFrameworkCompetenciesAndGroupsSPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE FUNCTION [dbo].[GetSelfAssessmentSummaryForCandidate]
        ///(
        ///	@CandidateID int,
        ///	@SelfAssessmentID int
        ///)
        ///RETURNS @ResTable TABLE 
        ///(
        ///	CompetencyGroupID int,
        ///	Confidence float,
        ///	Relevance float
        ///)
        ///
        ///AS	  
        ///BEGIN
        ///INSERT INTO @ResTable
        ///	SELECT CompetencyGroupID, [1] AS Confidence, [2] AS Relevance
        ///FROM   (SELECT comp.CompetencyGroupID, sar.AssessmentQuestionID, sar.Result*1.0 AS Result
        ///             FROM    Competencies AS comp INNER JOIN
        ///                           SelfAssessmentResults AS sar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilteredSPs {
            get {
                return ResourceManager.GetString("FilteredSPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]    Script Date: 14/10/2020 10:02:34 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 05/10/2020
        ///-- Description:	Returns active available customisations for centre v5 adds SelfAssessments.
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetActiveAvailableV5 {
            get {
                return ResourceManager.GetString("GetActiveAvailableV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]    Script Date: 22/06/2021 09:46:28 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 05/10/2020
        ///-- Description:	Returns active available customisations for centre v5 adds SelfAssessments.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFilter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEEDLS_667_GetActiveAvailableCustomisationsForCentreFiltered_V5_Signposting_DOWN {
            get {
                return ResourceManager.GetString("HEEDLS_667_GetActiveAvailableCustomisationsForCentreFiltered_V5_Signposting_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]    Script Date: 17/11/2021 16:40:41 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 05/10/2020
        ///-- Description:	Returns active available customisations for centre v5 adds SelfAssessments.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFilter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEEDLS_667_GetActiveAvailableCustomisationsForCentreFiltered_V5_Signposting_UP {
            get {
                return ResourceManager.GetString("HEEDLS_667_GetActiveAvailableCustomisationsForCentreFiltered_V5_Signposting_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V6]    Script Date: 24/01/2023 15:00:41 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 24/01/2023
        ///-- Description:	Returns active available for delegate enrolment based on original GetActiveAvailableCustomisationsForCentreFiltered_V6 sproc but adjusted for user account refactor and filters properly for cate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string td_1043_getactivitiesforenrolment {
            get {
                return ResourceManager.GetString("td_1043_getactivitiesforenrolment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V6]    Script Date: 24/01/2023 15:31:20 ******/
        ///DROP PROCEDURE [dbo].[GetActivitiesForDelegateEnrolment]
        ///GO
        ///
        ///
        ///.
        /// </summary>
        internal static string td_1043_getactivitiesforenrolment_down {
            get {
                return ResourceManager.GetString("td_1043_getactivitiesforenrolment_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[Candidates]    Script Date: 2/22/2023 09:29:54 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		
        ///-- Modified date: 22/02/2023
        ///-- =============================================
        ///
        ///ALTER   VIEW [dbo].[Candidates] AS
        ///SELECT dbo.DelegateAccounts.ID       AS CandidateID,
        ///       dbo.DelegateAccounts.Active,
        ///       dbo.DelegateAccounts.CentreID,
        ///       dbo.Users.FirstName,
        ///       dbo.Users.LastName,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string td_1131_alterviewcandidatesadduserid_down {
            get {
                return ResourceManager.GetString("td_1131_alterviewcandidatesadduserid_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[Candidates]    Script Date: 2/22/2023 09:29:54 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		
        ///-- Modified date: 22/02/2023
        ///-- =============================================
        ///
        ///ALTER   VIEW [dbo].[Candidates] AS
        ///SELECT dbo.DelegateAccounts.ID       AS CandidateID,
        ///       dbo.DelegateAccounts.Active,
        ///       dbo.DelegateAccounts.CentreID,
        ///       dbo.Users.FirstName,
        ///       dbo.Users.LastName,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string td_1131_alterviewcandidatesadduserid_up {
            get {
                return ResourceManager.GetString("td_1131_alterviewcandidatesadduserid_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --TD-1220-AddSystemVersioning_SelfAssessmentResultSupervisorVerifications
        ///--Add versioning in SelfAssessmentResultSupervisorVerifications table
        ///ALTER TABLE SelfAssessmentResultSupervisorVerifications
        ///    ADD
        ///        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
        ///            CONSTRAINT DF_SelfAssessmentResultSupervisorVerifications_SysStart DEFAULT SYSUTCDATETIME()
        ///      , SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
        ///            CONSTRAINT DF_SelfAssessmentResultSupervisorVerif [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_1220_AddSystemVersioning_SelfAssessmentResultSupervisorVerifications {
            get {
                return ResourceManager.GetString("TD_1220_AddSystemVersioning_SelfAssessmentResultSupervisorVerifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --TD-1220-AddSystemVersioning_SelfAssessmentResultSupervisorVerifications
        ///-- Remove versioning from SelfAssessmentResultSupervisorVerifications table
        ///ALTER TABLE SelfAssessmentResultSupervisorVerifications SET (SYSTEM_VERSIONING = OFF);
        ///ALTER TABLE SelfAssessmentResultSupervisorVerifications DROP PERIOD FOR SYSTEM_TIME;
        ///ALTER TABLE [dbo].SelfAssessmentResultSupervisorVerifications DROP CONSTRAINT [DF_SelfAssessmentResultSupervisorVerifications_SysEnd];
        ///ALTER TABLE [dbo].SelfAssessmentResultSupervisorVe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_1220_RemoveSystemVersioning_SelfAssessmentResultSupervisorVerifications {
            get {
                return ResourceManager.GetString("TD_1220_RemoveSystemVersioning_SelfAssessmentResultSupervisorVerifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActivitiesForDelegateEnrolment]    Script Date: 22/05/2023 07:50:40 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 24/01/2023
        ///-- Description:	Returns active available for delegate enrolment based on original GetActiveAvailableCustomisationsForCentreFiltered_V6 sproc but adjusted for user account refactor and filters properly for category.
        ///-- ============= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string td_1610_update_getactivitiesfordelegateenrolment_proc_down {
            get {
                return ResourceManager.GetString("td_1610_update_getactivitiesfordelegateenrolment_proc_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActivitiesForDelegateEnrolment]    Script Date: 19/05/2023 16:40:12 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 24/01/2023
        ///-- Description:	Returns active available for delegate enrolment based on original GetActiveAvailableCustomisationsForCentreFiltered_V6 sproc but adjusted for user account refactor and filters properly for category.
        ///-- ============= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string td_1610_update_getactivitiesfordelegateenrolment_proc_up {
            get {
                return ResourceManager.GetString("td_1610_update_getactivitiesfordelegateenrolment_proc_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActivitiesForDelegateEnrolment]    Script Date: 01/06/2023 15:32:33 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 24/01/2023
        ///-- Description:	Returns active available for delegate enrolment based on original GetActiveAvailableCustomisationsForCentreFiltered_V6 sproc but adjusted for user account refactor and filters properly for category.
        ///-- ========= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_1766_GetActivitiesForDelegateEnrolmentTweak {
            get {
                return ResourceManager.GetString("TD_1766_GetActivitiesForDelegateEnrolmentTweak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActivitiesForDelegateEnrolment]    Script Date: 01/06/2023 15:32:33 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 24/01/2023
        ///-- Description:	Returns active available for delegate enrolment based on original GetActiveAvailableCustomisationsForCentreFiltered_V6 sproc but adjusted for user account refactor and filters properly for category.
        ///-- ========= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_1766_GetActivitiesForDelegateEnrolmentTweak_down {
            get {
                return ResourceManager.GetString("TD_1766_GetActivitiesForDelegateEnrolmentTweak_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetCurrentCoursesForCandidate_V2]    Script Date: 26/06/2023 08:04:53 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 16/12/2016
        ///-- Description:	Returns a list of active progress records for the candidate.
        ///-- Change 18/09/2018: Adds logic to exclude Removed courses from returned results.
        ///-- =============================================
        ///ALTER PROCEDU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_1766_GetCurrentCoursesForCandidateTweak {
            get {
                return ResourceManager.GetString("TD_1766_GetCurrentCoursesForCandidateTweak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetCurrentCoursesForCandidate_V2]    Script Date: 22/06/2023 14:49:50 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 16/12/2016
        ///-- Description:	Returns a list of active progress records for the candidate.
        ///-- Change 18/09/2018: Adds logic to exclude Removed courses from returned results.
        ///-- =============================================
        ///ALTER PROCEDURE [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_1766_GetCurrentCoursesForCandidateTweak_down {
            get {
                return ResourceManager.GetString("TD_1766_GetCurrentCoursesForCandidateTweak_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GroupCustomisation_Add_V2]    Script Date: 16/06/2023 09:17:01 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 22/10/2018
        ///-- Description:	Adds a customisation to a group and enrols all group delegates on the customisation if applicable.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GroupCustomisation_Add_V2]
        ///	-- Add the parameter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_1913_AlterGroupCustomisation_Add_V2_DOWN {
            get {
                return ResourceManager.GetString("TD_1913_AlterGroupCustomisation_Add_V2_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GroupCustomisation_Add_V2]    Script Date: 16/06/2023 09:17:01 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 22/10/2018
        ///-- Description:	Adds a customisation to a group and enrols all group delegates on the customisation if applicable.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GroupCustomisation_Add_V2]
        ///	-- Add the parameter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_1913_AlterGroupCustomisation_Add_V2_UP {
            get {
                return ResourceManager.GetString("TD_1913_AlterGroupCustomisation_Add_V2_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActivitiesForDelegateEnrolment]    Script Date: 05/07/2023 08:52:32 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 24/01/2023
        ///-- Description:	Returns active available for delegate enrolment based on original GetActiveAvailableCustomisationsForCentreFiltered_V6 sproc but adjusted for user account refactor and filters properly for category.
        ///-- ============= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_2094_GetActivitiesForDelegateEnrolmentDelegateStatusPropertyTweak {
            get {
                return ResourceManager.GetString("TD_2094_GetActivitiesForDelegateEnrolmentDelegateStatusPropertyTweak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActivitiesForDelegateEnrolment]    Script Date: 05/07/2023 09:33:56 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 24/01/2023
        ///-- Description:	Returns active available for delegate enrolment based on original GetActiveAvailableCustomisationsForCentreFiltered_V6 sproc but adjusted for user account refactor and filters properly for category.
        ///-- ============= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_2094_GetActivitiesForDelegateEnrolmentDelegateStatusPropertyTweak_down {
            get {
                return ResourceManager.GetString("TD_2094_GetActivitiesForDelegateEnrolmentDelegateStatusPropertyTweak_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 03/07/2023
        ///-- Description:	Populate the ReportSelfAssessmentActivityLog table with recent activity
        ///-- =============================================
        ///CREATE OR ALTER PROCEDURE PopulateReportSelfAssessmentActivityLog
        ///
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///   DECLARE @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_2117_CreatePopulateReportSelfAssessmentActivityLog_SP {
            get {
                return ResourceManager.GetString("TD_2117_CreatePopulateReportSelfAssessmentActivityLog_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[AdminUsers]    Script Date: 2/6/2023 22:11:41 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		
        ///-- Modified date: 02/06/2023
        ///-- Description:	Return the admin user details
        ///-- =============================================
        ///
        ///ALTER VIEW [dbo].[AdminUsers] AS
        ///SELECT dbo.AdminAccounts.ID                    AS AdminID,
        ///       null                                    AS Login,
        ///       dbo.Users.PasswordHas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string td_264_alterviewadminusersaddcentrename_down {
            get {
                return ResourceManager.GetString("td_264_alterviewadminusersaddcentrename_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[AdminUsers]    Script Date: 2/6/2023 22:11:41 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		
        ///-- Modified date: 02/06/2023
        ///-- Description:	Return the admin user details
        ///-- =============================================
        ///
        ///ALTER VIEW [dbo].[AdminUsers] AS
        ///SELECT dbo.AdminAccounts.ID                    AS AdminID,
        ///       null                                    AS Login,
        ///       dbo.Users.PasswordHas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string td_264_alterviewadminusersaddcentrename_up {
            get {
                return ResourceManager.GetString("td_264_alterviewadminusersaddcentrename_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V6]    Script Date: 29/09/2022 19:11:04 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		Manish Agarwal
        ///-- Create date: 26/09/2022
        ///-- Description:	Returns active available customisations for centre v6 adds SelfAssessments.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_786_GetSelfRegisteredFlag_DOWN {
            get {
                return ResourceManager.GetString("TD-786-GetSelfRegisteredFlag_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[GetActiveAvailableCustomisationsForCentreFiltered_V5]    Script Date: 08/12/2022 13:00:15 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Kevin Whittaker
        ///-- Create date: 05/10/2020
        ///-- Description:	Returns active available customisations for centre v5 adds SelfAssessments.
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[GetActiveAvailableCustomisationsForCentreFilter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD_786_GetSelfRegisteredFlag_UP {
            get {
                return ResourceManager.GetString("TD-786-GetSelfRegisteredFlag_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW AdminUsers
        ///    GO
        ///DROP VIEW Candidates
        ///    GO
        ///.
        /// </summary>
        internal static string UAR_831_CreateViewsForAdminUsersAndCandidatesTables_DOWN {
            get {
                return ResourceManager.GetString("UAR-831-CreateViewsForAdminUsersAndCandidatesTables-DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW AdminUsers AS
        ///SELECT dbo.AdminAccounts.ID                    AS AdminID,
        ///       null                                    AS Login,
        ///       dbo.Users.PasswordHash                  AS Password,
        ///       dbo.AdminAccounts.CentreID,
        ///       dbo.AdminAccounts.IsCentreAdmin         AS CentreAdmin,
        ///       0                                       AS ConfigAdmin,
        ///       dbo.AdminAccounts.IsReportsViewer       AS SummaryReports,
        ///       dbo.AdminAccounts.IsSuperAdmin          AS UserAdmin,
        ///       dbo.Us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UAR_831_CreateViewsForAdminUsersAndCandidatesTables_UP {
            get {
                return ResourceManager.GetString("UAR-831-CreateViewsForAdminUsersAndCandidatesTables-UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @dbName NVARCHAR(128) = DB_NAME()
        ///DECLARE @defaultPath NVARCHAR(500) = CONVERT(NVARCHAR(500), SERVERPROPERTY(&apos;InstanceDefaultDataPath&apos;))
        ///DECLARE @snapshotTime NVARCHAR(12) = FORMAT(GETDATE(), &apos;yyyyMMddHHmm&apos;)
        ///
        ///DECLARE @snapSql NVARCHAR(4000) = &apos;CREATE DATABASE &apos; + @dbName + &apos;_&apos; + @snapshotTime + &apos; ON 
        ///( NAME = mbdbx101, FILENAME = &apos;&apos;&apos; + @defaultPath + @dbName + &apos;_&apos; + @snapshotTime + &apos;&apos;&apos;),
        ///( NAME = mbdbx101files, FILENAME = &apos;&apos;&apos; + @defaultPath + @dbName + &apos;_filestream1_&apos; + @snapshotTime + &apos;&apos;&apos;)
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UAR_858_SnapshotData_UP {
            get {
                return ResourceManager.GetString("UAR_858_SnapshotData_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @dbName NVARCHAR(128) = DB_NAME()
        ///DECLARE @snapshotName NVARCHAR(128) = CONVERT(NVARCHAR(128), (SELECT TOP 1 name FROM sys.databases WHERE NAME LIKE @dbName + &apos;_2%&apos; ORDER BY create_date DESC))
        ///
        ///DECLARE @adminSql NVARCHAR(4000) = &apos;UPDATE AdminAccounts
        ///SET 
        ///    Login_deprecated = snapAA.Login_deprecated,
        ///    Password_deprecated = snapAA.Password_deprecated,
        ///    CentreID = snapAA.CentreID,
        ///    IsCentreAdmin = snapAA.IsCentreAdmin,
        ///    ConfigAdmin_deprecated = snapAA.ConfigAdmin_deprecated,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UAR_859_PopulateUsersTableFromAccountsTables_DOWN {
            get {
                return ResourceManager.GetString("UAR_859_PopulateUsersTableFromAccountsTables_DOWN", resourceCulture);
            }
        }
    }
}
